unstable_features = true
control_brace_style = "AlwaysNextLine"
brace_style = "AlwaysNextLine"
merge_imports = true
enum_discrim_align_threshold = 32
struct_field_align_threshold = 32
use_field_init_shorthand = true
edition = "2018"
wrap_comments = true
