[package]
name = "fnd"
version = "0.1.0"
authors = ["Steven Le Rouzic <steven.lerouzic@gmail.com>"]
edition = "2018"

[lib]
name = "fnd"
path = "lib.rs"

[target.'cfg(windows)'.dependencies]
win32 = { path = "../win32" }