[package]
name = "gfx"
version = "0.1.0"
authors = ["Steven Le Rouzic <steven.lerouzic@gmail.com>"]
edition = "2018"

[dependencies]
vk = { path = "../vk" }
fnd = { path = "../fnd" }
wsi = { path = "../wsi" }
